accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import google_login, home, create, logouts, store, painel, dologin, dashboard, changepass, changePassword, depositar
app_name='accounts'

urlpatterns = [
    path('admin/', admin.site.urls),  # Admin site
    path('', painel, name='painel'),  # Home page
    path('create/', create, name='create'),  # Create account
    path('store/', store, name='store'),  # Store data
    path('dologin/', dologin, name='dologin'),  # Login
    path('dashboard/', dashboard, name='dashboard'),  # User dashboard
    path('logouts/', logouts, name='logouts'),  # Logout
    path('changepass/', changepass, name='changepass'),  # Change password for user
    path('changepassword/', changePassword, name='changepassword'),  # Change password
    path('depositar/', depositar, name='depositar'),  # Deposit money
    path('login/google/', google_login, name='google_login'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('loteria/',include(('loteria.urls', 'loteria'), namespace='loteria')),
    path('jogodobicho/',include(('jogodobicho.urls', 'jogodobicho'), namespace='jogodobicho')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

jogodobicho/urls.py
from django.contrib import admin
from django.urls import path
from jogodobicho.views import jogodobicho,jogodobicho2,sorteio_,procura_ganhador
name_app='jogodobicho'
urlpatterns = [
    path('jogo/', jogodobicho,name='inicio'),
    path('jogodobicho2/', jogodobicho2,name='jogodobicho2'),
    path('sortear/',sorteio_,name='sortear'),
    path('procurar_ganhador',procura_ganhador,name='ganhadores')
]

loteria/urls.py
from django.urls import path,include
from . import views
app_name='loteria'

urlpatterns = [
    #path('', views.page_login, name='page_login'),
    path('aposta/',views.form_jogo,name='apostar'),
    path('cadastra_aposta/',views.cadastra_aposta,name='cadastra_numero'),
    path('sortear/',views.sorteia_numero, name='sortear'),
    path('ver_ganhadores/',views.procura_ganhador,name='testar_ganhadores'),
    path('sacar/',views.sacar,name='sacar'),
    #path('autenticar_cliente/',views.autenticar_cliente,name='autenticar_cliente'),
    #path('logout_usuario', views.logout_usuario, name='logout_usuario'),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
#from django.contrib.admin.sites import User
class Usuario(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    saldo=models.FloatField()
    def __str__(self):
        return self.usuario.username

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Usuario
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import time

# Verifica se o usuário está logado e retorna o objeto 'Usuario'
@login_required
def verifica_login(request):
    return request.user  # Retorna a instância do usuário autenticado

# Consulta saldo de um usuário
def consultaSaldo(id_user):
    user_model = User.objects.get(id=id_user)
    usuario = Usuario.objects.get(usuario=user_model)
    return usuario

# Página inicial
def home(request):
    return render(request, '../../accounts/templates/home.html')

# Formulário de cadastro
def create(request):
    return render(request, '../../accounts/templates/create.html')

# Inserção dos dados do usuário no banco
def store(request):
    data = {}
    try:
        # Verifica se já existe um usuário com o mesmo nome ou senha
        usuario_aux = User.objects.get(username=request.POST['user'])
        usuario_aux2 = User.objects.filter(password=request.POST['password'])

        if usuario_aux or usuario_aux2:
            data['msg'] = 'Usuario ou Senha já existem!'
            data['class'] = 'alert-danger'
    except User.DoesNotExist:
        # Cria um novo usuário se não existir
        user = User.objects.create_user(request.POST['user'], request.POST['email'], request.POST['password'])
        user.first_name = request.POST['name']
        user.save()

        # Cria o objeto 'Usuario' associado ao novo usuário
        query_user = User.objects.get(id=user.id)
        usu = Usuario.objects.create(usuario=query_user, saldo=0)
        data['msg'] = 'Usuário Cadastrado com sucesso! Faça Login.'
        data['class'] = 'alert-success'

    return render(request, '../../accounts/templates/painel.html', data)

# Formulário painel de login
def painel(request):
    return render(request, '../../accounts/templates/painel.html')

# Processa login tradicional
def dologin(request):
    data = {}
    user = authenticate(username=request.POST['user'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect("accounts:dashboard")
    else:
        data['msg'] = 'Usuário ou Senha inválidos!'
        data['class'] = 'alert-danger'
        return render(request, '../../accounts/templates/painel.html', data)

# Dashboard após o login
@login_required
def dashboard(request):
    usuario = consultaSaldo(request.user.id)  # Use o ID do User autenticado

    if not usuario:
        return redirect("accounts:painel")  # Redireciona se não encontrar o usuário

    # Agora você pode acessar o saldo
    saldo = usuario.saldo

    context = {
        'usuario': usuario,
        'valor': saldo,
        # Outros dados para o contexto
    }

    return render(request, 'dashboard/home.html', context)
# Logout
def logouts(request):
    logout(request)
    return redirect('accounts:painel')

# Alterar senha
@login_required
def changepass(request):
    user = request.user
    return render(request, '../../accounts/templates/dashboard/changepassword.html', {'user': user})

# Processa a alteração de senha
@login_required
def changePassword(request):
    senha_atual = request.POST.get("senha_atual")
    nova_senha = request.POST.get("nova_senha")
    user = User.objects.get(username=request.user.username)

    context = {}
    if user.check_password(senha_atual):  # Verifica se a senha atual está correta
        user.set_password(nova_senha)  # Altera a senha
        user.save()
        context = {
            'msg': "Senha Alterada com Sucesso!",
            'class': "alert-success"
        }
    else:
        context = {
            'msg': "Senha atual inválida!",
            'class': "alert-danger"
        }

    return render(request, '../../accounts/templates/dashboard/changepassword.html', context)

# Função de depósito
@login_required
def depositar(request):
    usuario = consultaSaldo(request.user.id)
    print('Saldo atual:', usuario.saldo)
    valor = request.POST.get('valor')

    if valor and float(valor) > 0:
        usuario.saldo = usuario.saldo + float(valor)
        usuario.save()
        print('Saldo novo:', usuario.saldo)
    else:
        print('Valor inválido para depósito!')

    return redirect('accounts:dashboard')

# Login com Google
def google_login(request):
    # Redireciona para o login com o Google
    time.sleep(2)
    return redirect('social:begin', 'google-oauth2')

# Callback após o login com Google
def google_login_callback(request):
    # Aqui tratamos o retorno do login via Google
    google_user_data = request.user  # Dados do Google

    # Busque o usuário no banco de dados ou crie um novo
    try:
        user = User.objects.get(username=google_user_data.username)
    except User.DoesNotExist:
        # Se não existir, cria um novo usuário no Django
        user = User.objects.create_user(
            username=google_user_data.username,
            email=google_user_data.email,
            password=None  # Login social não precisa de senha
        )
        user.save()

    # Verifique se o objeto 'Usuario' já existe, se não, cria-o
    try:
        usuario = Usuario.objects.get(usuario=user)
    except Usuario.DoesNotExist:
        usuario = Usuario.objects.create(usuario=user, saldo=0.0)

    # Autentica o usuário
    login(request, user)
    return redirect('accounts:dashboard')

accounts/templates/dashboard/changepassword.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
   <meta charset="UTF-8">
   <title>Mudar Senha</title>
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="icon" type="icon" href="{% static 'icons/icon_animal_lottery.ico' %}" />
</head>

<body class="login1">
   <form name="formPainel" id="formPainel" method="post" action="{% url 'accounts:/changepassword/' %}">
      <div class="main-login">

         {% csrf_token %}
         <div class="left-login">
            <h1>Altere sua Senha<br>e volte a jogar.<br></h1>
            <img src="{% static 'css/bichos.svg' %}" class="left-login-image" alt="Bichos a solta">
         </div>

         <div class="right-login">
            <div class="card-login">
               <div class="textfield">
                  <label for="usu">Usuario</label>
                  <input name="usu" id="usu" type="text" value="{{user}}" readonly>
               </div>
               <h1>Alterar Senha</h1>
               <div class="textfield">
                  <label for="senha_atual">Senha Atual</label>
                  <input name="senha_atual" id="senha_atual" type="password" name="password" id="password"
                     placeholder="Senha">
               </div>
               <div class="textfield">
                  <label for="nova_senha">Nova Senha</label>
                  <input name="nova_senha" id="nova_senha" type="password" name="password" id="password"
                     placeholder="Senha">
               </div>
               <button type="submit" class="btn-login">Alterar</button>

               <p class="cadastrar">Ao invés disso, <a href="{% url 'accounts:/logouts/'%}" class="link-info">volte ao
                     início.</a></p>

               {% if msg %}
               <div class="alert {{class}}">
                  {{msg}}
               </div>
               {% endif %}
            </div>
         </div>
      </div>
   </form>

   <!-- Java Script-->
   <script src="{% static 'js/javascript.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
</body>

accounts/templates/dashboard/home.html
{% extends 'main.html' %}

{% block content %}
{% if request.user.is_authenticated %}

<div class="center">
   <div class="box">
      <div class="card" style="width: 25vw;height: 70vh;">
         <img src="../../../accounts/static/img/bicho.jpg" class="card-img-top" alt="Jogo do Bicho">
         <div class="card-body">
            <h5 class="card-title">Jogo do Bicho</h5>
            <p class="card-text texto">Os jogadores podem fazer suas apostas escolhendo diferentes animais e os
               prêmios são
               decididos durante o sorteio. Se suas apostas são ganhadoras, você conseguirá grandes prêmios!</p>
            <a href="{% url 'jogodobicho:inicio' %}" class="btn btn-primary">Jogar</a>
         </div>
      </div>
   </div>

   <div class="box">
      <div class="card" style="width: 25vw;height: 70vh;">
         <img src="../../../accounts/static/img/loteria.jpg" class="card-img-top" alt="Jogo do Bicho">
         <div class="card-body">
            <h5 class="card-title">Loteria</h5>
            <p class="card-text texto">Os jogadores podem fazer suas apostas escolhendo os números que concorrerão ao
               sorteio.
               Se suas apostas são ganhadoras, você conseguirá grandes prêmios!.</p>
            <a href="{% url 'loteria:apostar' %}" class="btn btn-primary">Jogar</a>
         </div>
      </div>
   </div>

</div>

{% else %}
Você não tem acesso a essa área!
{% endif %}

{% endblock %}