accounts/urls.py
from django.contrib import admin
from django.urls import path
from accounts.views import google_login, home, create, logouts, store, painel, dologin, dashboard, changepass, changePassword, depositar
app_name='accounts'

urlpatterns = [
    path('admin/', admin.site.urls),  # Admin site
    path('', painel, name='painel'),  # Home page
    path('create/', create, name='create'),  # Create account
    path('store/', store, name='store'),  # Store data
    path('dologin/', dologin, name='dologin'),  # Login
    path('dashboard/', dashboard, name='dashboard'),  # User dashboard
    path('logouts/', logouts, name='logouts'),  # Logout
    path('changepass/', changepass, name='changepass'),  # Change password for user
    path('changepassword/', changePassword, name='changepassword'),  # Change password
    path('depositar/', depositar, name='depositar'),  # Deposit money
    path('login/google/', google_login, name='google_login'),
]

core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('loteria/',include(('loteria.urls', 'loteria'), namespace='loteria')),
    path('jogodobicho/',include(('jogodobicho.urls', 'jogodobicho'), namespace='jogodobicho')),
    path('oauth/', include('social_django.urls', namespace='social')),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
#from django.contrib.admin.sites import User
class Usuario(models.Model):
    usuario=models.OneToOneField(User, on_delete=models.CASCADE)
    saldo=models.FloatField()
    def __str__(self):
        return self.usuario.username

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Usuario
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import time

# Verifica se o usuário está logado e retorna o objeto 'Usuario'
@login_required
def verifica_login(request):
    return request.user  # Retorna a instância do usuário autenticado

# Consulta saldo de um usuário
def consultaSaldo(id_user):
    user_model = User.objects.get(id=id_user)
    usuario = Usuario.objects.get(usuario=user_model)
    return usuario

# Página inicial
def home(request):
    return render(request, '../../accounts/templates/home.html')

# Formulário de cadastro
def create(request):
    return render(request, '../../accounts/templates/create.html')

# Inserção dos dados do usuário no banco
def store(request):
    data = {}
    try:
        # Verifica se já existe um usuário com o mesmo nome ou senha
        usuario_aux = User.objects.get(username=request.POST['user'])
        usuario_aux2 = User.objects.filter(password=request.POST['password'])

        if usuario_aux or usuario_aux2:
            data['msg'] = 'Usuario ou Senha já existem!'
            data['class'] = 'alert-danger'
    except User.DoesNotExist:
        # Cria um novo usuário se não existir
        user = User.objects.create_user(request.POST['user'], request.POST['email'], request.POST['password'])
        user.first_name = request.POST['name']
        user.save()

        # Cria o objeto 'Usuario' associado ao novo usuário
        query_user = User.objects.get(id=user.id)
        usu = Usuario.objects.create(usuario=query_user, saldo=0)
        data['msg'] = 'Usuário Cadastrado com sucesso! Faça Login.'
        data['class'] = 'alert-success'

    return render(request, '../../accounts/templates/painel.html', data)

# Formulário painel de login
def painel(request):
    return render(request, '../../accounts/templates/painel.html')

# Processa login tradicional
def dologin(request):
    data = {}
    user = authenticate(username=request.POST['user'], password=request.POST['password'])
    if user is not None:
        login(request, user)
        return redirect("accounts:dashboard")
    else:
        data['msg'] = 'Usuário ou Senha inválidos!'
        data['class'] = 'alert-danger'
        return render(request, '../../accounts/templates/painel.html', data)

# Dashboard após o login
@login_required
def dashboard(request):
    usuario = consultaSaldo(request.user.id)  # Use o ID do User autenticado

    if not usuario:
        return redirect("accounts:painel")  # Redireciona se não encontrar o usuário

    # Agora você pode acessar o saldo
    saldo = usuario.saldo

    context = {
        'usuario': usuario,
        'valor': saldo,
        # Outros dados para o contexto
    }

    return render(request, 'dashboard/home.html', context)
# Logout
def logouts(request):
    logout(request)
    return redirect('accounts:painel')

# Alterar senha
@login_required
def changepass(request):
    user = request.user
    return render(request, '../../accounts/templates/dashboard/changepassword.html', {'user': user})

# Processa a alteração de senha
@login_required
def changePassword(request):
    senha_atual = request.POST.get("senha_atual")
    nova_senha = request.POST.get("nova_senha")
    user = User.objects.get(username=request.user.username)

    context = {}
    if user.check_password(senha_atual):  # Verifica se a senha atual está correta
        user.set_password(nova_senha)  # Altera a senha
        user.save()
        context = {
            'msg': "Senha Alterada com Sucesso!",
            'class': "alert-success"
        }
    else:
        context = {
            'msg': "Senha atual inválida!",
            'class': "alert-danger"
        }

    return render(request, '../../accounts/templates/dashboard/changepassword.html', context)

# Função de depósito
@login_required
def depositar(request):
    usuario = consultaSaldo(request.user.id)
    print('Saldo atual:', usuario.saldo)
    valor = request.POST.get('valor')

    if valor and float(valor) > 0:
        usuario.saldo = usuario.saldo + float(valor)
        usuario.save()
        print('Saldo novo:', usuario.saldo)
    else:
        print('Valor inválido para depósito!')

    return redirect('accounts:dashboard')

# Login com Google
def google_login(request):
    # Redireciona para o login com o Google
    time.sleep(2)
    return redirect('social:begin', 'google-oauth2')

# Callback após o login com Google
def google_login_callback(request):
    # Aqui tratamos o retorno do login via Google
    google_user_data = request.user  # Dados do Google

    # Busque o usuário no banco de dados ou crie um novo
    try:
        user = User.objects.get(username=google_user_data.username)
    except User.DoesNotExist:
        # Se não existir, cria um novo usuário no Django
        user = User.objects.create_user(
            username=google_user_data.username,
            email=google_user_data.email,
            password=None  # Login social não precisa de senha
        )
        user.save()

    # Verifique se o objeto 'Usuario' já existe, se não, cria-o
    try:
        usuario = Usuario.objects.get(usuario=user)
    except Usuario.DoesNotExist:
        usuario = Usuario.objects.create(usuario=user, saldo=0.0)

    # Autentica o usuário
    login(request, user)
    return redirect('accounts:dashboard')

accounts/templates/create.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Cadastre-se</title>
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <link rel="icon" type="icon" href="{% static 'icons/icon_animal_lottery.ico' %}" />
    <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
</head>

<body class="login1">
   <form name="form-users" id="formUsers" method="post" action="/store/">
      <div class="main-login">
         
         {% csrf_token %}
         <div class="left-login">
            <h1>Cadastro<br>Animal Lottery<br></h1>
            <img src="{% static 'css/bichos.svg' %}" class="left-login-image" alt="Bichos a solta">    
         </div>

         <div class="right-login">
            <div class="card-login">
               <h1>Cadastre-se</h1>
               <div class="textfield">
                  <!--<label for="name">Nome</label>-->
                  <input type="text" name="name" id="name" placeholder="Nome">

                  <!--<label for="usuario">Usuário</label>-->
                  <input type="text" name="user" id="user" placeholder="Usuário">
               </div>

               <div class="textfield">
                  <!--<label for="senha">Senha</label>-->
                  <input type="password" name="password" id="password" placeholder="Senha">

                  <!--<label for="senha">Repita a Senha</label>-->
                  <input type="password" name="password-conf" id="password-conf" placeholder="Repita a Senha">
               </div>

               <div class="textfield">
                  <!--<label for="email">Email</label>-->
                  <input type="email"name="email" id="email" placeholder="Email">
               </div>
                  <button class="btn-login">Cadastrar</button>
               <p class="cadastrar">Já tem uma conta? <a href="{% url 'accounts:/painel/' %}" class="link-info">Fazer Login</a></p>
               
               {% if msg %}
            <div class="alert {{class}}">
               {{msg}}
            </div>
         {% endif %}
            </div>
         </div>
      </div>
   </form>
   <!-- Java Script-->
   <script src="{% static 'js/javascript.js' %}"></script>
</body>

accounts/templates/home.html
{% extends 'main.html' %}

{% block content %}
{% if request.user.is_authenticated %}
<title>Dashboard</title>

<div class="center">
   <div class="box">
      <div class="card" style="width: 25rem;">
         <img src="../../static/img/bicho.jpg" class="card-img-top" alt="Jogo do Bicho">
         <div class="card-body">
            <h5 class="card-title">Jogo do Bicho</h5>
            <p class="card-text">Os jogadores podem fazer suas apostas escolhendo diferentes animais e os prêmios são
               decididos durante o sorteio. Se suas apostas são ganhadoras, você conseguirá grandes prêmios!</p>
            <a href="#" class="btn btn-primary">Jogar</a>
         </div>
      </div>
   </div>

   <div class="box">
      <div class="card" style="width: 25rem;">
         <img src="../../static/img/loteria.jpg" class="card-img-top" alt="Jogo do Bicho">
         <div class="card-body">
            <h5 class="card-title">Loteria</h5>
            <p class="card-text">Os jogadores podem fazer suas apostas escolhendo os números que concorrerão ao sorteio.
               Se suas apostas são ganhadoras, você conseguirá grandes prêmios!.</p>
            <a href="loteria" class="btn btn-primary">Jogar</a>
         </div>
      </div>
   </div>

</div>

{% else %}
Você não tem acesso a essa área!
{% endif %}

{% endblock %}

accounts/templates/main.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <link href="{% static 'css/navbar.css' %}" rel="stylesheet">
  <link href="{% static 'css/cards.css' %}" rel="stylesheet">
  <link href="../../../accounts/static/css/loteria.css" rel="stylesheet">
  <link href="{% static 'css/bicho.css' %}" rel="stylesheet">
  <link rel="icon" type="icon" href="{% static 'icons/icon_animal_lottery.ico' %}" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <title>Animal Lottery</title>
  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />

</head>

<body STYLE="background-image: url(../../accounts/static/img/cover.jpg)">
  <!--LOGO-->
  <div class="navbar navbar-expand-lg">
    <div class="container-fluid">
      <a class="logo" href="{% url 'accounts:dashboard' %}">
        <img src="{% static 'img/animal_lottery.png' %}" alt="Animal Lottery" width="128vw" height="40vh">
      </a>

      <!--SALDO-->
      <div class="boxs">
        <div class="saldo">
          <span class="symbol">R$ </span>{{valor}}
        </div>


        <div class="depositar">
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#exampleModal"
            data-bs-whatever="@getbootstrap">Depositar</button>
        </div>
      </div>

      <!--JANELA MODAL-->
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Adicionar Saldo</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <form action="{% url 'accounts:depositar' %}" method="POST" enctype="multipart/form-data">
                {%csrf_token%}
                <div class="mb-3">
                  <label for="recipient-name" class="col-form-label">Valor:</label>
                  <input name="valor" id="valor" type="text" class="form-control" maxlength="12" placeholder="0,00">
                  <input name="usu" id="usu" type="text" value="{{user.id}}" style="display: none;">
                  <div class="modal-footer">
                    <button type="reset" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                    <button type="submit" class="btn btn-primary">Depositar</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>


      <!--USUÁRIO-->
      <div class="dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
          aria-expanded="false">
          <img src="{% static 'icons/user.ico' %}" class="rounded-circle" height="25" alt="Usuário" loading="lazy" />
        </a>

        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
          <li><a class="dropdown-item" type="button" data-bs-toggle="modal" data-bs-target="#exampleModal"
              data-bs-whatever="@getbootstrap">Adicionar Saldo</a></li>
          <li><a class="dropdown-item" href="{% url 'accounts:changepass' %}">Mudar Senha</a></li>
          <li>
            <hr class="dropdown-divider">
          </li>
          <li><a class="dropdown-item" href="{% url 'accounts:logouts' %}">Sair</a></li>
        </ul>
      </div>



    </div>

  </div>

  {% block content %}

  {% endblock %}

  <script type="text/javascript">
    function CountChecks(maxchecked, latestcheck) {
      var checkboxes = document.querySelectorAll('input[type="checkbox"]');
      var count = 0;

      // Conta quantos checkboxes estão selecionados
      checkboxes.forEach(function (checkbox) {
        if (checkbox.checked) {
          count++;
        }
      });

      // Se o número exceder o máximo permitido
      if (count > maxchecked) {
        alert('Desculpe, só é permitido selecionar ' + maxchecked + ' números.');
        latestcheck.checked = false; // Desmarca o último checkbox selecionado
      }
    }
  </script>

  <script src="../../accounts/static/js/javascript.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

accounts/templates/painel.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
   <meta charset="UTF-8">
   <title>Login</title>
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   <link rel="icon" type="icon" href="{% static 'icons/icon_animal_lottery.ico' %}" />
   <link rel="stylesheet" href="https://unpkg.com/bootstrap@5.3.3/dist/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://unpkg.com/bs-brain@2.0.4/components/logins/login-6/assets/css/login-6.css">
   <!--<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">-->
</head>

<body class="login1">
   <form name="formPainel" id="formPainel" method="post" action="/dologin/">
      <div class="main-login">

         {% csrf_token %}
         <div class="left-login">
            <h1>Bem-Vindo<br>ao Animal Lottery<br></h1>
            <img src="{% static 'css/bichos.svg' %}" class="left-login-image" alt="Bichos a solta">
         </div>

         <div class="right-login">
            <div class="card-login">
               <h1>Login</h1>
               <div class="textfield">
                  <label for="usuario">Usuário</label>
                  <input type="text" name="user" id="user" placeholder="Usuário">
               </div>
               <div class="textfield">
                  <label for="senha">Senha</label>
                  <input type="password" name="password" id="password" placeholder="Senha">
               </div>
               <button class="btn-login">Entrar</button>
               <h2 class="text-white"> OU </h2>

               <a href="{% url 'accounts:google_login' %}" class="botao-google">
                  <!-- tenho uma imagem baixada pra colocar no lugar do svg -->

                  <img src="{% static 'img/google.png' %}" alt="google" width="30">
                  <span class="ms-2 fs-6 text-uppercase text-black">Entrar Com Google</span>
               </a>

               <p class="cadastrar">Não tem uma conta? <a href="/create/" class="link-info">Cadastrar-se</a></p>

               {% if msg %}
               <div class="alert {{class}}">
                  {{msg}}
               </div>
               {% endif %}
            </div>
         </div>
      </div>
   </form>


   <!-- <form name="formPainel" id="formPainel" method="post" action="/dologin/">
      <div class="col-6 mt-4 m-auto">
         {% if msg %}
            <div class="alert {{class}}">
               {{msg}}
            </div>
         {% endif %}


         {% csrf_token %}
         <input class="form-control mt-4" type="text" name="user" id="user" placeholder="Nome do Usuário">
         <input class="form-control mt-4" type="password" name="password" id="password" placeholder="Senha">
         <input class="btn btn-dark mt-4" type="submit" value="Entrar">
      </div>
   </form> (FORM COM TOKEN E MENSAGEM)-->

   <!-- Java Script-->
   <script src="{% static 'js/javascript.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"></script>
</body>